# Generated by Django 6.1 on 2026-09-14 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('sd', 'Sekolah Dasar'), ('smp', 'Sekolah Menengah Pertama'), ('sma', 'Sekolah Menengah Atas'), ('kuliah', 'Perguruan Tinggi')], default='sd', max_length=20)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_year'],
            },
        ),
    ]
